# Generated by Django 5.2.8 on 2025-12-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciamedica',
            name='archivo',
        ),
        migrations.AddField(
            model_name='licenciamedica',
            name='created_by',
            field=models.ForeignKey(help_text='Usuario que registró la licencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
