# Generated by Django 5.2.11 on 2026-02-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0002_remove_licenciamedica_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciamedica',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='licencias/'),
        ),
    ]
