# Generated by Django 5.2.9 on 2026-04-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_licenciamedica_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedica',
            name='tipo',
            field=models.CharField(choices=[('LICENCIA', 'Licencia Médica'), ('PERMISO', 'Permiso sin Goce de Remuneraciones'), ('PRENATAL', 'Licencia Prenatal'), ('POSTNATAL', 'Licencia Postnatal')], default='LICENCIA', max_length=20),
        ),
    ]
