# Generated by Django 5.2.9 on 2026-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_alter_licenciamedica_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedica',
            name='tipo',
            field=models.CharField(choices=[('LICENCIA', 'Licencia Médica'), ('PERMISO', 'Permiso sin Goce de Remuneraciones'), ('PRENATAL', 'Licencia Prenatal'), ('POSTNATAL', 'Licencia Postnatal'), ('POSTNATAL_PARENTAL', 'Permiso Postnatal Parental')], default='LICENCIA', max_length=20),
        ),
    ]
