# Generated by Django 5.2.9 on 2026-05-11 02:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0006_alter_licenciamedica_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedica',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=core.storage.EncryptedFileSystemStorage(), upload_to='licencias/'),
        ),
    ]
