# Generated by Django 5.2.9 on 2026-09-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0007_alter_licenciamedica_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedica',
            name='dias',
            field=models.PositiveIntegerField(help_text='Para Licencia por Fallecimiento, se cuentan días hábiles (lunes a viernes, sin feriados).'),
        ),
        migrations.AlterField(
            model_name='licenciamedica',
            name='tipo',
            field=models.CharField(choices=[('LICENCIA', 'Licencia Médica'), ('PERMISO', 'Permiso sin Goce de Remuneraciones'), ('PRENATAL', 'Licencia Prenatal'), ('POSTNATAL', 'Licencia Postnatal'), ('POSTNATAL_PARENTAL', 'Permiso Postnatal Parental'), ('FALLECIMIENTO', 'Licencia por Fallecimiento')], default='LICENCIA', max_length=20),
        ),
    ]
