# Generated by Django 5.2.8 on 2025-12-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_funcionario',
            field=models.CharField(blank=True, choices=[('DOCENTE', 'Docente'), ('ASISTENTE', 'Asistente de la Educación')], help_text='Aplica solo para rol Funcionario', max_length=20, null=True),
        ),
    ]
