# Generated by Django 5.2.9 on 2025-12-07 15:09

from django.db import migrations


def normalize_existing_ruts(apps, schema_editor):
    """Normalize all existing user RUTs to Chilean format with dots"""
    CustomUser = apps.get_model('users', 'CustomUser')

    def normalize_rut_dotted(rut):
        """Normalize a RUT to Chilean format with dots: 12.345.678-K"""
        if not rut:
            return rut

        rut = str(rut).upper()
        rut = rut.replace('.', '').replace(' ', '')

        if '-' not in rut:
            if len(rut) >= 2:
                rut = rut[:-1] + '-' + rut[-1]
            else:
                rut = rut + '-'

        parts = rut.split('-')
        if len(parts) == 2:
            cuerpo, dv = parts
            if dv not in '0123456789K':
                if len(cuerpo) > 0:
                    dv = cuerpo[-1]
                    cuerpo = cuerpo[:-1]
                    rut = cuerpo + '-' + dv

        # Formatear con puntos (formato chileno)
        cuerpo, dv = rut.split('-')
        cuerpo_reversed = cuerpo[::-1]
        formatted = []
        for i, char in enumerate(cuerpo_reversed):
            formatted.append(char)
            if (i + 1) % 3 == 0 and i + 1 < len(cuerpo_reversed):
                formatted.append('.')

        cuerpo_formatted = ''.join(formatted[::-1])
        rut_formatted = f"{cuerpo_formatted}-{dv}"

        return rut_formatted

    # Update all users with non-normalized RUTs
    for user in CustomUser.objects.all():
        normalized_rut = normalize_rut_dotted(user.run)
        if normalized_rut != user.run:
            user.run = normalized_rut
            user.save(update_fields=['run'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_tipo_funcionario'),
    ]

    operations = [
    ]
