# Generated by Django 5.2.9 on 2025-12-07 15:19

from django.db import migrations


def convert_ruts_to_dotted_format(apps, schema_editor):
    """Convert all existing user RUTs to Chilean dotted format"""
    CustomUser = apps.get_model('users', 'CustomUser')

    def format_rut_with_dots(rut):
        """Format a RUT with dots in Chilean format: 12.345.678-K"""
        if not rut:
            return rut

        # Remove existing dots and spaces
        rut = str(rut).replace('.', '').replace(' ', '')

        # Ensure it has dash
        if '-' not in rut:
            if len(rut) >= 2:
                rut = rut[:-1] + '-' + rut[-1]

        # Split into body and check digit
        cuerpo, dv = rut.split('-')

        # Format body with dots (from right to left: 3, 3, rest)
        cuerpo_reversed = cuerpo[::-1]
        formatted = []
        for i, char in enumerate(cuerpo_reversed):
            formatted.append(char)
            if (i + 1) % 3 == 0 and i + 1 < len(cuerpo_reversed):
                formatted.append('.')

        cuerpo_formatted = ''.join(formatted[::-1])
        return f"{cuerpo_formatted}-{dv}"

    # Update all users to dotted format
    for user in CustomUser.objects.all():
        current_rut = str(user.run)
        dotted_rut = format_rut_with_dots(user.run)
        if dotted_rut != current_rut:
            try:
                user.run = dotted_rut
                user.save(update_fields=['run'])
                print(f"Updated RUT for user {user.get_full_name()}: {current_rut} -> {dotted_rut}")
            except Exception as e:
                print(f"Could not update RUT for user {user.get_full_name()}: {e}")
                # Skip this user if there's a constraint violation
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_normalize_existing_ruts'),
    ]

    operations = [
        migrations.RunPython(convert_ruts_to_dotted_format),
    ]
