# Generated by Django 5.2.9 on 2026-03-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_convert_ruts_to_dotted_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Correo electrónico de acceso', max_length=254, null=True, unique=True),
        ),
    ]
