# Generated by Django 5.2.9 on 2026-03-10 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del grupo de correo', max_length=100, unique=True)),
                ('correo', models.EmailField(help_text='Correo del grupo (ej: grupo@dominio.cl)', max_length=254, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del propósito del grupo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, help_text='Miembros del grupo', related_name='grupos_correo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Correo',
                'verbose_name_plural': 'Grupos de Correo',
                'ordering': ['nombre'],
            },
        ),
    ]
