# Generated by Django 5.2.11 on 2026-03-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_grupocorreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20),
        ),
    ]
