# Generated by Django 5.2.11 on 2026-03-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioTelefonico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(help_text='Nombre del lugar (ej: Dirección, Secretarias, Biblioteca)', max_length=100)),
                ('anexo', models.CharField(help_text='Número de anexo (ej: 101, 202)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorio_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Directorio Telefónico',
                'verbose_name_plural': 'Directorio Telefónico',
                'ordering': ['lugar'],
            },
        ),
    ]
