# Generated by Django 5.2.9 on 2026-03-11 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_directoriotelefonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que fue bloqueado el usuario', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó el bloqueo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Si está marcado, el usuario no podrá iniciar sesión'),
        ),
    ]
