# Generated by Django 5.2.9 on 2026-03-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funcion',
            field=models.CharField(blank=True, choices=[('ASISTENTE_AULA', 'Asistente de Aula'), ('ASISTENTE_REEMPLAZO', 'Asistente Reemplazo'), ('ASISTENTE_SOCIAL', 'Asistente Social'), ('AUXILIAR', 'Auxiliar'), ('AYUDANTE_BIBLIOTECA', 'Ayudante de Biblioteca'), ('DIRECTOR', 'Director (a)'), ('DOCENTE_AULA', 'Docente de Aula'), ('DOCENTE_DIFERENCIAL', 'Docente Diferencial'), ('DOCENTE_REEMPLAZO', 'Docente Reemplazo'), ('ENCARGADO_BIBLIOTECA', 'Encargado (a) de Biblioteca'), ('ENCARGADO_FOTOCOPIA', 'Encargado de Fotocopia'), ('ENFERMERO', 'Enfermero (a)'), ('FONOAUDIOLOGO', 'Fonoaudiólogo (a)'), ('INFORMATICO', 'Informático'), ('INSPECTOR', 'Inspector (a)'), ('INSPECTOR_GENERAL', 'Inspector General'), ('JEFE_UTP', 'Jefe (a) de UTP'), ('PSICOPEDAGOGO', 'Psicopedagogo (a)'), ('PSICOLOGO', 'Psicólogo (a)'), ('SECRETARIA', 'Secretaria'), ('SERENO', 'Sereno'), ('TECNICO_DEPORTIVO', 'Técnico Deportivo'), ('TECNICO_DIFERENCIAL', 'Técnico Diferencial'), ('TECNICO_PARSULO', 'Técnico en Párvulo'), ('TERAPEUTA_OCUPACIONAL', 'Terapeuta Ocupacional')], help_text='Función o cargo específico del usuario', max_length=30, null=True),
        ),
    ]
