# Generated by Django 5.2.9 on 2026-08-04 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_baja_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='funcion',
            field=models.CharField(blank=True, choices=[('ASISTENTE_AULA', 'Asistente de Aula'), ('ASISTENTE_REEMPLAZO', 'Asistente Reemplazo'), ('ASISTENTE_SOCIAL', 'Asistente Social'), ('AUXILIAR', 'Auxiliar'), ('AYUDANTE_BIBLIOTECA', 'Ayudante de Biblioteca'), ('DIRECTOR', 'Director (a)'), ('DOCENTE_AULA', 'Docente de Aula'), ('DOCENTE_DIFERENCIAL', 'Docente Diferencial'), ('DOCENTE_REEMPLAZO', 'Docente Reemplazo'), ('EDUCADORA_DIFERENCIAL', 'Educadora Diferencial'), ('EDUCADORA_PARVULOS', 'Educadora de Párvulos'), ('ENCARGADO_BIBLIOTECA', 'Encargado (a) de Biblioteca'), ('ENCARGADO_CONVIVENCIA', 'Encargado (a) de Convivencia'), ('ENCARGADO_FOTOCOPIA', 'Encargado de Fotocopia'), ('ENFERMERO', 'Enfermero (a)'), ('FONOAUDIOLOGO', 'Fonoaudiólogo (a)'), ('INFORMATICO', 'Informático'), ('INSPECTOR', 'Inspector (a)'), ('INSPECTOR_GENERAL', 'Inspector General'), ('JEFE_UTP', 'Jefe (a) de UTP'), ('MONITOR_TALLER', 'Monitor Taller'), ('PSICOPEDAGOGO', 'Psicopedagogo (a)'), ('PSICOLOGO', 'Psicólogo (a)'), ('SECRETARIA', 'Secretaria'), ('SERENO', 'Sereno'), ('TECNICO_DEPORTIVO', 'Técnico Deportivo'), ('TECNICO_DIFERENCIAL', 'Técnico Diferencial'), ('TECNICO_PARSULO', 'Técnico en Párvulo'), ('TERAPEUTA_OCUPACIONAL', 'Terapeuta Ocupacional')], help_text='Función o cargo específico del usuario', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='BajaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Motivo de la baja (ej: Reemplazo, Licencia, Baja médica)', max_length=100)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la baja')),
                ('fecha_termino', models.DateField(blank=True, help_text='Fecha de fin de la baja (opcional si es indefinida)', null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('justificacion', models.TextField(blank=True, help_text='Justificación adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'SECRETARIA', 'DIRECTOR', 'DIRECTIVO']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_creadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Funcionario al que se aplica este período de baja', on_delete=django.db.models.deletion.CASCADE, related_name='baja_periodos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Periodo de Baja',
                'verbose_name_plural': 'Periodos de Baja',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_termino__isnull', True), ('fecha_termino__gte', models.F('fecha_inicio')), _connector='OR'), name='check_fecha_termino_gte_inicio')],
            },
        ),
    ]
