# Generated by Django 5.2.9 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_baja_periodo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajaperiodo',
            name='motivo',
            field=models.CharField(
                choices=[
                    ('Reemplazo', 'Reemplazo'),
                    ('Licencia', 'Licencia'),
                    ('Baja médica', 'Baja médica'),
                    ('Vacaciones', 'Vacaciones'),
                    ('Capacitación', 'Capacitación'),
                    ('Otro', 'Otro')
                ],
                help_text='Motivo de la baja',
                max_length=100
            ),
        ),
    ]