# Generated by Django 5.2.9 on 2026-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_bajaperiodo_motivo_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notifications_disabled',
            field=models.BooleanField(default=False, help_text='Si está marcado, se silenciarán las notificaciones por correo'),
        ),
    ]
