services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_DATABASE=sgpal_db
      - SQL_USER=sgpal_user
      - SQL_PASSWORD=Sgpal2025Secure*
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,[::1]
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
      - SECURE_SSL_REDIRECT=False

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sgpal_user
      - POSTGRES_PASSWORD=Sgpal2025Secure*
      - POSTGRES_DB=sgpal_db

volumes:
  postgres_data:
  media_data:
