# Generated by Django 5.2.9 on 2026-08-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Desactivando silencia todas las notificaciones por correo')),
                ('liquidations_notifications_enabled', models.BooleanField(default=True, help_text='Notificar cuando se suben liquidaciones')),
                ('attendance_notifications_enabled', models.BooleanField(default=True, help_text='Notificar cuando se cargan asistencias')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
