# Generated by Django 5.2.9 on 2026-09-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_system_settings_and_notifications_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='director_daily_summary_enabled',
            field=models.BooleanField(default=False, help_text='Enviar resumen diario de días administrativos y licencias a directores'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='director_daily_summary_time',
            field=models.CharField(default='07:45', help_text='Hora de envío del resumen diario (HH:MM)', max_length=5),
        ),
    ]
