# Generated by Django 5.2.9 on 2026-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('disponible_prestamo', models.BooleanField(default=True)),
                ('color_hex', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'verbose_name': 'Estado de Equipo',
                'verbose_name_plural': 'Estados de Equipos',
            },
        ),
        migrations.CreateModel(
            name='EstadoRegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_como_asistencia', models.BooleanField(default=True)),
                ('requiere_justificacion', models.BooleanField(default=False)),
                ('color_hex', models.CharField(default='#6B7280', help_text='Color para UI', max_length=7)),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_terminal', models.BooleanField(default=False, help_text='Estado final (no hay más transacciones)')),
                ('permite_edicion', models.BooleanField(default=True)),
                ('color_hex', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'verbose_name': 'Estado de Solicitud de Permiso',
                'verbose_name_plural': 'Estados de Solicitudes de Permisos',
            },
        ),
        migrations.CreateModel(
            name='JornadaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('horas', models.FloatField(default=0, help_text='Horas que representa esta jornada')),
            ],
            options={
                'verbose_name': 'Jornada Laboral',
                'verbose_name_plural': 'Jornadas Laborales',
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nivel_acceso', models.PositiveIntegerField(default=1, help_text='Nivel de acceso (1=mínimo, 5=administrador)')),
                ('puede_administrar', models.BooleanField(default=False)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('puede_ver_todos', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='TipoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cuenta_como_asistencia', models.BooleanField(default=True)),
                ('descuenta_dias', models.BooleanField(default=False)),
                ('color_hex', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de Día',
                'verbose_name_plural': 'Tipos de Días',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del catálogo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('activo', models.BooleanField(default=True, help_text='Si el catálogo está activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Funcionario',
                'verbose_name_plural': 'Tipos de Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(help_text='Primer día del período')),
                ('fecha_termino', models.DateField(help_text='Último día del período')),
                ('activo', models.BooleanField(default=True)),
                ('cerrado', models.BooleanField(default=False, help_text='Período cerrado para modificaciones')),
            ],
            options={
                'verbose_name': 'Período de Liquidación',
                'verbose_name_plural': 'Períodos de Liquidaciones',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('mes', 'anio')},
            },
        ),
    ]
