# Generated by Django 5.2.8 on 2025-12-05 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='imports/usuarios/%Y/%m/')),
                ('fecha_importacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_registros', models.IntegerField(default=0)),
                ('exitosos', models.IntegerField(default=0)),
                ('fallidos', models.IntegerField(default=0)),
                ('log_errores', models.TextField(blank=True)),
                ('importado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Usuarios',
                'verbose_name_plural': 'Importaciones de Usuarios',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTH', 'Autenticación'), ('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('APPROVE', 'Aprobación'), ('REJECT', 'Rechazo'), ('ERROR', 'Error'), ('EXPORT', 'Exportación'), ('IMPORT', 'Importación')], max_length=20)),
                ('accion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'tipo'], name='admin_dashb_timesta_a60c6b_idx'), models.Index(fields=['usuario', '-timestamp'], name='admin_dashb_usuario_b0c4a7_idx')],
            },
        ),
    ]
