# Generated by Django 5.2.9 on 2026-04-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Efemeride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Actividad o Conmemoración')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efemerides_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Efeméride',
                'verbose_name_plural': 'Efemérides',
                'ordering': ['fecha'],
            },
        ),
    ]
