# Generated by Django 5.2.9 on 2025-12-08 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_convert_ruts_to_dotted_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField(help_text='Hora de entrada asignada (ej: 08:00:00)')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=15, help_text='Minutos de tolerancia para considerar puntual')),
                ('activo', models.BooleanField(default=True, help_text='Si el horario está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Horario de Funcionario',
                'verbose_name_plural': 'Horarios de Funcionarios',
                'ordering': ['funcionario__last_name', 'funcionario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada_real', models.TimeField(blank=True, help_text='Hora de entrada registrada por el reloj control', null=True)),
                ('minutos_retraso', models.IntegerField(default=0, help_text='Minutos de retraso calculados')),
                ('estado', models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('SIN_HORARIO', 'Sin Horario Asignado')], default='AUSENTE', max_length=20)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='users.customuser')),
                ('horario_asignado', models.ForeignKey(blank=True, help_text='Horario que tenía asignado en esa fecha', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.horariofuncionario')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_procesados', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', 'funcionario__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='registroasistencia',
            constraint=models.UniqueConstraint(fields=('funcionario', 'fecha'), name='unique_funcionario_fecha'),
        ),
    ]
