# Generated by Django 5.2.9 on 2025-12-08 02:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registroasistencia',
            name='unique_funcionario_fecha',
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('funcionario', 'fecha')},
        ),
    ]
