# Generated by Django 5.2.9 on 2025-12-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_registroasistencia_unique_funcionario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_salida_real',
            field=models.TimeField(blank=True, help_text='Hora de salida registrada por el reloj control', null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_trabajados',
            field=models.IntegerField(blank=True, help_text='Minutos trabajados calculados', null=True),
        ),
    ]
