# Generated by Django 5.2.9 on 2025-12-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_add_hora_salida_minutos_trabajados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='hora_salida_real',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='minutos_trabajados',
        ),
    ]
