# Generated by Django 5.2.9 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_remove_registroasistencia_hora_salida_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_salida_real',
            field=models.TimeField(blank=True, help_text='Hora de salida registrada por el reloj control', null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_trabajados',
            field=models.IntegerField(blank=True, help_text='Minutos totales trabajados (calculado automáticamente)', null=True),
        ),
    ]
