# Generated by Django 5.2.9 on 2025-12-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_add_hora_salida_minutos_trabajados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='fecha_justificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='justificacion_manual',
            field=models.TextField(blank=True, help_text='Justificación manual agregada por administrador'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='justificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_justificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('DIA_ADMINISTRATIVO', 'Día Administrativo'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('DIA_FESTIVO', 'Día Festivo'), ('SIN_HORARIO', 'Sin Horario Asignado')], default='AUSENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='AlegacionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo de la alegación')),
                ('evidencia', models.FileField(blank=True, help_text='Archivo de evidencia opcional', null=True, upload_to='alegaciones/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador')),
                ('fecha_alegacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('registro_asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alegacion', to='asistencia.registroasistencia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alegaciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alegación de Asistencia',
                'verbose_name_plural': 'Alegaciones de Asistencia',
                'ordering': ['-fecha_alegacion'],
            },
        ),
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día festivo', unique=True)),
                ('nombre', models.CharField(help_text='Nombre del día festivo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_festivos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'ordering': ['fecha'],
            },
        ),
    ]
