# Generated by Django 5.2.9 on 2026-03-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_registroasistencia_fecha_justificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('MEDIO_DIA', 'Medio Día Administrativo'), ('DIA_ADMINISTRATIVO', 'Día Administrativo'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('DIA_FESTIVO', 'Día Festivo'), ('SIN_HORARIO', 'Sin Horario Asignado')], default='AUSENTE', max_length=20),
        ),
    ]
