# Generated by Django 5.2.9 on 2026-03-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_add_medio_dia_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(help_text='Año escolar (ej: 2026)', unique=True)),
                ('sem1_inicio', models.DateField(help_text='Fecha de inicio del primer semestre')),
                ('sem1_fin', models.DateField(help_text='Fecha de fin del primer semestre')),
                ('sem2_inicio', models.DateField(help_text='Fecha de inicio del segundo semestre')),
                ('sem2_fin', models.DateField(help_text='Fecha de fin del segundo semestre')),
                ('activo', models.BooleanField(default=False, help_text='Si este es el año escolar activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anos_escolares_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
                'ordering': ['-ano'],
            },
        ),
    ]
