# Generated by Django 5.2.9 on 2026-04-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_add_sin_marcacion_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('SIN_MARCACION_ENTRADA', 'Sin Marcación de Entrada'), ('MEDIO_DIA', 'Medio Día Administrativo'), ('DIA_ADMINISTRATIVO', 'Día Administrativo'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('DIA_FESTIVO', 'Día Festivo'), ('DIA_LIBRE', 'Día Libre'), ('SIN_HORARIO', 'Sin Horario Asignado')], default='AUSENTE', max_length=25),
        ),
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora de entrada para este día', null=True)),
                ('hora_salida', models.TimeField(blank=True, help_text='Hora de salida esperada para este día', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el funcionario debe trabajar este día')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='asistencia.horariofuncionario')),
            ],
            options={
                'verbose_name': 'Día de Horario',
                'verbose_name_plural': 'Días de Horario',
                'ordering': ['dia_semana'],
                'unique_together': {('horario', 'dia_semana')},
            },
        ),
    ]
