# Generated by Django 5.2.9 on 2026-04-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_registroasistencia_estado_diahorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha a la que aplica este horario excepcional', unique=True)),
                ('hora_entrada', models.TimeField(blank=True, help_text='Hora de entrada obligatoria (dejar en blanco si no aplica entrada)', null=True)),
                ('hora_salida', models.TimeField(blank=True, help_text='Hora de salida autorizada (dejar en blanco si no aplica salida)', null=True)),
                ('motivo', models.CharField(help_text='Motivo de este horario excepcional (ej: Día del Profesor, Corte de agua)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_excepcionales_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Excepcional',
                'verbose_name_plural': 'Horarios Excepcionales',
                'ordering': ['-fecha'],
            },
        ),
    ]
