# Generated by Django 5.2.9 on 2026-04-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_horarioexcepcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariofuncionario',
            name='tolerancia_minutos',
        ),
    ]
