# Generated by Django 5.2.9 on 2026-05-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_remove_tolerancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PUNTUAL', 'Puntual'), ('RETRASO', 'Retraso'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado'), ('SIN_MARCACION_ENTRADA', 'Sin Marcación de Entrada'), ('MEDIO_DIA', 'Medio Día Administrativo'), ('DIA_ADMINISTRATIVO', 'Día Administrativo'), ('LICENCIA_MEDICA', 'Licencia Médica'), ('DIA_FESTIVO', 'Día Festivo'), ('SIN_HORARIO', 'Sin Horario Asignado'), ('SIN_DATA', 'Sin Datos')], default='AUSENTE', max_length=25),
        ),
    ]
