# Generated by Django 5.2.9 on 2026-05-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_alter_registroasistencia_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diahorario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='diahorario',
            name='semana_tipo',
            field=models.IntegerField(blank=True, choices=[(1, 'Semana 1'), (2, 'Semana 2')], help_text='Para horarios rotativos (Semana 1/2). Si es nulo, aplica a todas las semanas.', null=True),
        ),
        migrations.AlterField(
            model_name='diahorario',
            name='hora_salida',
            field=models.TimeField(blank=True, help_text='Hora de salida para este día', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='diahorario',
            unique_together={('horario', 'dia_semana', 'semana_tipo')},
        ),
    ]
