# Generated by Django 5.2.9 on 2026-07-01 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0015_add_baja_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaAsignadaSereno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año de la semana asignada')),
                ('semana_iso', models.IntegerField(help_text='Número de semana ISO (1-53)')),
                ('turno', models.IntegerField(choices=[(1, 'Semana 1 (Impar)'), (2, 'Semana 2 (Par)')], help_text='Turno asignado para esa semana')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la asignación')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanas_asignadas_creadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(help_text='Funcionario sereno al que se asigna la semana', on_delete=django.db.models.deletion.CASCADE, related_name='semanas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semana Asignada a Sereno',
                'verbose_name_plural': 'Semanas Asignadas a Serenos',
                'ordering': ['funcionario__last_name', 'anio', 'semana_iso'],
                'unique_together': {('funcionario', 'anio', 'semana_iso')},
            },
        ),
    ]
