# Generated by Django 5.2.9 on 2026-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0016_asignar_semana_sereno'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioexcepcional',
            name='es_para_serenos',
            field=models.BooleanField(default=False, help_text='Si está marcado, este horario excepcional solo aplica a funcionarios con cargo sereno'),
        ),
    ]
