# Generated by Django 5.2.11 on 2026-02-14 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Computador de Escritorio'), ('TABLET', 'Tablet'), ('IMPRESORA', 'Impresora'), ('MONITOR', 'Monitor'), ('PROYECTOR', 'Proyector'), ('CELULAR', 'Celular'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('numero_inventario', models.CharField(max_length=100, unique=True, verbose_name='Número de Inventario')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('ASIGNADO', 'Asignado'), ('EN_REPARACION', 'En Reparación'), ('BAJA', 'De Baja')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de Adquisición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones del Préstamo')),
                ('activo', models.BooleanField(default=True, verbose_name='Préstamo Activo')),
                ('asignado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_asignados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='equipos.equipo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_prestados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo de Equipo',
                'verbose_name_plural': 'Préstamos de Equipos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
