# Generated by Django 5.2.9 on 2026-02-22 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FallaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Falla')),
                ('estado', models.CharField(choices=[('REPORTADA', 'Reportada'), ('EN_REVISION', 'En Revisión'), ('REPARADA', 'Reparada'), ('BAJA', 'De Baja / Reemplazo'), ('DENEGADA', 'No Procede')], default='REPORTADA', max_length=20, verbose_name='Estado de la Falla')),
                ('comentarios_tecnicos', models.TextField(blank=True, verbose_name='Comentarios Técnicos / Resolución')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='equipos.equipo', verbose_name='Equipo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario que Reporta')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Falla de Equipo',
                'verbose_name_plural': 'Fallas de Equipos',
                'ordering': ['-fecha_reporte'],
            },
        ),
    ]
