# Generated by Django 5.2.9 on 2026-03-10 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_fallaequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANTENIMIENTO_PREVENTIVO', 'Mantenimiento Preventivo'), ('REPARACION', 'Reparación / Mantenimiento Correctivo'), ('ACTUALIZACION', 'Actualización de Hardware/Software'), ('INSPECCION', 'Inspección Rutinaria'), ('OTRO', 'Otro / Observación')], max_length=50, verbose_name='Tipo de Mantenimiento / Hito')),
                ('fecha', models.DateField(verbose_name='Fecha del Hito')),
                ('descripcion', models.TextField(verbose_name='Descripción / Observaciones')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Asociado (Opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitos_creados', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Hito de Mantenimiento',
                'verbose_name_plural': 'Hitos de Mantenimiento',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
