# Generated by Django 5.2.9 on 2026-03-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_hitomantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Computador de Escritorio'), ('TABLET', 'Tablet'), ('IMPRESORA', 'Impresora'), ('MONITOR', 'Monitor'), ('PROYECTOR', 'Proyector'), ('CELULAR', 'Celular'), ('CONTROL_REMOTO', 'Control Remoto'), ('PARLANTE', 'Parlante'), ('LAPIZ_INTERACTIVO', 'Lápiz Interactivo'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Equipo'),
        ),
    ]
