# Generated by Django 5.2.9 on 2026-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_inventario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Inventario'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serie'),
        ),
    ]
