# Generated by Django 5.2.9 on 2026-03-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_alter_equipo_modelo_alter_equipo_numero_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_inventario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Inventario'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
    ]
