# Generated by Django 5.2.9 on 2026-08-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0017_lugarequipo_equipo_lugar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamoequipo',
            name='es_prestamo_diario',
            field=models.BooleanField(default=False, verbose_name='¿Es Préstamo Diario?'),
        ),
        migrations.AddField(
            model_name='prestamoequipo',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Devolución Real'),
        ),
        migrations.CreateModel(
            name='TicketBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Asunto')),
                ('descripcion', models.TextField(verbose_name='¿Qué se hizo? (Descripción del trabajo)')),
                ('categoria', models.CharField(choices=[('SOPORTE_FUNCIONARIO', 'Soporte a Funcionario'), ('MANTENIMIENTO_EQUIPO', 'Mantenimiento / Reparación de Equipo'), ('AUDIOVISUAL_SALAS', 'Configuración / Instalación Audiovisual'), ('REDES_CONECTIVIDAD', 'Redes / Conectividad / Wifi'), ('SOFTWARE_PLATAFORMAS', 'Software / Cuentas / Plataformas'), ('IMPRESION_FOTOCOPIA', 'Impresión / Escáner / Fotocopia'), ('REVISION_PREVENTIVA', 'Revisión Preventiva'), ('OTRO', 'Otra Actividad / Requerimiento')], default='SOPORTE_FUNCIONARIO', max_length=40, verbose_name='Categoría de Actividad')),
                ('lugar_personalizado', models.CharField(blank=True, max_length=150, verbose_name='Lugar Personalizado (si no está en lista)')),
                ('estado', models.CharField(choices=[('RESUELTO', 'Resuelto / Finalizado'), ('EN_PROCESO', 'En Proceso'), ('PENDIENTE', 'Pendiente / Abierto')], default='RESUELTO', max_length=20, verbose_name='Estado del Ticket')),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20, verbose_name='Prioridad')),
                ('fecha_actividad', models.DateField(verbose_name='Fecha de la Actividad')),
                ('hora_actividad', models.TimeField(blank=True, null=True, verbose_name='Hora de la Actividad')),
                ('resolucion', models.TextField(blank=True, verbose_name='Detalle de Resolución / Observaciones Finales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_registrados_bitacora', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_bitacora', to='equipos.equipo', verbose_name='Equipo Involucrado (Opcional)')),
                ('falla_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_derivados', to='equipos.fallaequipo', verbose_name='Falla Reportada Asociada')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Atendido / Solicitante')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='equipos.lugarequipo', verbose_name='Lugar / Ubicación')),
            ],
            options={
                'verbose_name': 'Ticket / Bitácora TI',
                'verbose_name_plural': 'Tickets y Bitácora TI',
                'ordering': ['-fecha_actividad', '-fecha_creacion'],
            },
        ),
    ]
