# Generated by Django 5.2.8 on 2025-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='archivo_justificacion',
            field=models.FileField(blank=True, help_text='Documento de respaldo (PDF o JPG)', null=True, upload_to='solicitudes/'),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='observacion',
            field=models.TextField(blank=True, help_text='Motivo o justificación de la solicitud'),
        ),
    ]
