# Generated by Django 5.2.8 on 2025-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_solicitudpermiso_archivo_justificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón del rechazo (solo si es rechazado)'),
        ),
    ]
