# Generated by Django 5.2.9 on 2026-03-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_solicitudpermiso_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Indica si un permiso fuera de plazo ha sido desbloqueado por un directivo'),
        ),
    ]
