# Generated by Django 5.2.9 on 2025-12-07 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0004_solicitudpermiso_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Razón de la cancelación (solo si es cancelado)'),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
