# Generated by Django 5.2.9 on 2025-12-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='liquidaciones/%Y/%m/')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación de Sueldo',
                'verbose_name_plural': 'Liquidaciones de Sueldo',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
