# Generated by Django 5.2.9 on 2025-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0001_initial'),
    ]

    operations = [
        # Índices para mejorar performance en consultas frecuentes
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['funcionario', 'anio'], name='liquidacion_funcionario_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['-anio', '-mes'], name='liquidacion_anio_mes_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['funcionario'], name='liquidacion_funcionario_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['anio'], name='liquidacion_anio_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['mes'], name='liquidacion_mes_idx'),
        ),
    ]
