# Generated by Django 5.2.9 on 2025-12-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='liquidacion',
            name='liquidacion_funcionario_anio_idx',
        ),
        migrations.RemoveIndex(
            model_name='liquidacion',
            name='liquidacion_anio_mes_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='liquidacion',
            name='liquidacion_funcionario_idx',
        ),
        migrations.RemoveIndex(
            model_name='liquidacion',
            name='liquidacion_anio_idx',
        ),
        migrations.RemoveIndex(
            model_name='liquidacion',
            name='liquidacion_mes_idx',
        ),
    ]
