# Generated by Django 5.2.9 on 2026-05-11 02:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidaciones', '0003_remove_liquidacion_liquidacion_funcionario_anio_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='archivo',
            field=models.FileField(storage=core.storage.EncryptedFileSystemStorage(), upload_to='liquidaciones/%Y/%m/'),
        ),
    ]
